[[settings]]
name = "volume"
default = ""
help = "volume=<integer> Set the startup volume. 0 means silence, 100 means no volume reduction or amplification. Negative values can be passed for compatibility, but are treated as 0. Since mpv 0.18.1, this always controls the internal mixer (aka \"softvol\")."

[[settings]]
name = "screen"
default = ""
help = "screen=<default|0-32> In multi-monitor configurations (i.e. a single desktop that spans across multiple displays), this option tells mpv which screen to display the video on. Default: default."

[[settings]]
name = "osd-playing-msg"
default = ""
width = 300
help = "osd-playing-msg=<value> Show a message on OSD when playback starts. The string is expanded for properties, e.g. --osd-playing-msg='file: ${filename}' will show the message file: followed by a space and the currently played filename."
helpurl = "https://mpv.io/manual/master/#property-expansion"

[[settings]]
name = "fullscreen"
alias = "fs"
default = "no"
help = "fullscreen=<yes|no>, fs=<yes|no> Start the player in fullscreen mode. Default: no."
options = [{ name = "yes" }, { name = "no", text = "no (Default)" }]

[[settings]]
name = "hwdec"
default = "no"
helpurl = "https://mpv.io/manual/master/#options-hwdec"
help = "hwdec=<mode> Specify the hardware video decoding API that should be used if possible. Whether hardware decoding is actually done depends on the video codec. If hardware decoding is not possible, mpv will fall back on software decoding."
options = [{ name = "no", text = "no (Default)", help = "always use software decoding (Default)" },
           { name = "auto",         help = "enable best hw decoder (see below)" },
           { name = "yes",          help = "exactly the same as auto" },
           { name = "auto-copy",    help = "enable best hw decoder with copy-back (see below)" },
           { name = "dxva2",        help = "requires --vo=gpu with --gpu-context=d3d11, --gpu-context=angle or --gpu-context=dxinterop (Windows only)" },
           { name = "dxva2-copy",   help = "copies video back to system RAM (Windows only)" },
           { name = "d3d11va",      help = "requires --vo=gpu with --gpu-context=d3d11 or --gpu-context=angle (Windows 8+ only)" },
           { name = "d3d11va-copy", help = "copies video back to system RAM (Windows 8+ only)" },
           { name = "cuda",         help = "requires --vo=gpu (Any platform CUDA is available)" },
           { name = "cuda-copy",    help = "copies video back to system RAM (Any platform CUDA is available)" },
           { name = "nvdec",        help = "requires --vo=gpu (Any platform CUDA is available)" },
           { name = "nvdec-copy",   help = "copies video back to system RAM (Any platform CUDA is available)" },
           { name = "crystalhd",    help = "copies video back to system RAM (Any platform supported by hardware)" },
           { name = "rkmpp",        help = "requires --vo=gpu (some RockChip devices only)" }]

[[settings]]
name = "vo"
default = "gpu"
helpurl = "https://mpv.io/manual/master/#video-output-drivers-vo"
help = "gpu=<mode> Video output drivers to be used. Default = gpu."
options = [{ name = "direct3d", help = "Video output driver that uses the Direct3D interface" },
           { name = "gpu", text = "gpu (Default)", help = "General purpose, customizable, GPU-accelerated video output driver. It supports extended scaling methods, dithering, color management, custom shaders, HDR, and more. (Default)" }]

[[settings]]
name = "keep-open-pause"
default = "yes"
help = "keep-open-pause=<yes|no> If set to no, instead of pausing when --keep-open is active, just stop at end of file and continue playing forward when you seek backwards until end where it stops again. Default: yes."
options = [{ name = "yes", text = "yes (Default)" }, { name = "no" }]

[[settings]]
name = "keep-open"
default = "no"
help = "keep-open=<yes|no|always> Do not terminate when playing or seeking beyond the end of the file, and there is not next file to be played (and --loop is not used). Instead, pause the player. When trying to seek beyond end of the file, the player will attempt to seek to the last frame.\n\nNormally, this will act like set pause yes on EOF, unless the  --keep-open-pause=no option is set."
options = [{ name = "no", text = "no (Default)", help = "If the current file ends, go to the next file or terminate. (Default.)" },
           { name = "yes", help = "Don't terminate if the current file is the last playlist entry. Equivalent to --keep-open without arguments."},
		   { name = "always", help = "Like yes, but also applies to files before the last playlist entry. This means playback will never automatically advance to the next file."}]

[[settings]]
name = "loop-file"
alias = "loop"
default = ""
help = "loop-file=<N|inf|no>, loop=<N|inf|no> Loop a single file N times. inf means forever, no means normal playback. For compatibility, --loop-file and --loop-file=yes are also accepted, and are the same as --loop-file=inf.\n\nThe difference to --loop-playlist is that this doesn't loop the playlist, just the file itself. If the playlist contains only a single file, the difference between the two option is that this option performs a seek on loop, instead of reloading the file.\n\n--loop is an alias for this option."

[[settings]]
name = "screenshot-directory"
default = ""
width = 500
folder = true
help = "screenshot-directory=<value> Store screenshots in this directory. This path is joined with the filename generated by --screenshot-template. If the template filename is already absolute, the directory is ignored.\n\nIf the directory does not exist, it is created on the first screenshot. If it is not a directory, an error is generated when trying to write a screenshot.\n\nThis option is not set by default, and thus will write screenshots to the directory from which mpv was started. In pseudo-gui mode (see PSEUDO GUI MODE), this is set to the desktop."

[[settings]]
name = "input-ar-delay"
default = ""
help = "input-ar-delay=<integer> Delay in milliseconds before we start to autorepeat a key (0 to disable)."

[[settings]]
name = "input-ar-rate"
default = ""
help = "input-ar-rate=<integer> Number of key presses to generate per second on autorepeat."